lists exercise completed
NickelGit/ru-study-python pull request #1
Opened 2023-06-12 11:25 UTC by NickelGit

2023-06-13 07:53 UTC, aleksandr-semenov-dbp requested changes

2023-06-13 07:53 UTC, aleksandr-semenov-dbp commented on lists/lists.py
> +        max_number = max(input_list)
по условию max() использовать нельзя (здесь вызывается именно встроенная питоновская max())

2023-06-13 14:25 UTC, NickelGit commented on lists/lists.py
> +        max_number = max(input_list)
Большое спасибо! А я еще не мог понять почему в одном случае статик метод запустился только с указанием полного пути, а тут просто по имени подтянулся!)

2023-06-13 14:26 UTC, NickelGit commented on lists/lists.py
> +        max_number = max(input_list)
исправленное в коммите https://github.com/NickelGit/ru-study-python/pull/1/commits/6ea03c25f6f49eb44c2518bf331d4a86619522b1

2023-06-14 12:02 UTC, aleksandr-semenov-dbp approved these changes

2023-06-14 14:24 UTC, merged